; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	mandulaj/PZEM-004T-v30 @ ^1.1.2
	knolleary/PubSubClient@^2.8
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^7.2.2

; PARTISI UNTUK OTA (Memungkinkan update via WiFi)
board_build.partitions = min_spiffs.csv

; JALUR UPLOAD (Awalnya pake USB, nanti kalau mau OTA tinggal ganti ke IP)
upload_port = 192.168.4.1 
upload_flags = --auth=bapuk123