{
 "title": "PMSV1.1",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Voltage (V)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"v_ac\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Current (A)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"a_ac\")\r\n  |> last()\r\n  "
    }
   ]
  },
  {
   "title": "Panel Total Energy (kWh)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"e_ac\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Total Biaya Listrik",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyIDR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"e_ac\")\r\n  |> last()\r\n  |> map(fn: (r) => ({ r with _value: r._value * 1444.0 })) // Kali tarif PLN"
    }
   ]
  },
  {
   "title": "Power Ussage (Watts)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"w_ac\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Jam",
   "type": "stat",
   "gridPos": { "h": 17, "w": 22, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"server-bapuk\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> last()\r\n  // JURUS SAKTI: Geser waktu 7 jam ke depan (WIB)\r\n  |> timeShift(duration: 7h) \r\n  |> map(fn: (r) => ({\r\n      _value: strings.substring(v: string(v: r._time), start: 11, end: 19),\r\n      _field: \"jam_wib\"\r\n    }))"
    }
   ]
  },
  {
   "title": "SYSTEM STAT",
   "type": "stat",
   "gridPos": { "h": 17, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"server-bapuk\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pms_data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"v_ac\") // Field apa aja buat pemicu\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      _value: if exists r._time then \r\n                (if uint(v: now()) - uint(v: r._time) < uint(v: 60s) then 1 else 0)\r\n              else 0\r\n    }))\r\n  |> keep(columns: [\"_value\"])"
    }
   ]
  }
 ]
}